### PR TITLE
Confirming before deleting the credentials

### LINKED ISSUE #2: Ask before deleting the credentials or overwriting them

### PR DESCRIPTION
**Pull request by hemantwasthere**
Here I have used `input.js` to ask the user if he is sure or not to delete the credentials

Closes #2

### CODE REVIEW

**Comment by zeel-pathak** [comment]
Hey @hemantwasthere, Can you use ```async await``` instead of ``` then catch``` block and after using ```input``` call ``` over()``` so that it stops the read-line functionality, otherwise, in the long term it can throw an error. and do the changes in this pull request instead of creating a new one everytime.

**Comment by zeel-pathak** [comment]
And one more thing, can you compare ``` ans.toLowercase()``` with 'y' as well as 'yes', or you can slice the word to compare it with 'y'  only.

**Comment by hemantwasthere** [comment]
@zeel-pathak, Can you review the changes

**Comment by zeel-pathak** [comment]
@hemantwasthere  You are removing the data, but you are forgetting to overwrite the new data in place of old data, can you please also modify the info messages

**Comment by zeel-pathak** [comment]
Hey @hemantwasthere, Everything looks good to me, Thanks for your contribution.

I am merging your pull request, you can also star this repo and share about it online.

Happy hacking!

**Pull request merged**
